      common/probparams/
     &  CIRCLE_ROTATION_DELTA,CIRCLE_ROTATION_PARAB,
     &  SQUARE_ROTATION_DELTA,
     &  CELLG,FACEG,FLUXG
      integer 
     &  CIRCLE_ROTATION_DELTA,CIRCLE_ROTATION_PARAB,
     &  SQUARE_ROTATION_DELTA,
     &  CELLG,FACEG,FLUXG
