#define LCY  (1)

#define SYMM_BDY2D_COND_TYPE  (0)
#define WALL_BDY2D_COND_TYPE  (1)
#define FREE_BDY2D_COND_TYPE  (2)
#define DIRI_BDY2D_COND_TYPE  (3)
#define X_SYMM_CORNER_TYPE    (8)
#define R_SYMM_CORNER_TYPE    (9)
#define X_WALL_CORNER_TYPE    (10)
#define R_WALL_CORNER_TYPE    (11)
#define X_FREE_CORNER_TYPE    (12)
#define R_FREE_CORNER_TYPE    (13)
#define ZERO_BDY2D_COND_TYPE  (110)
#define OFLO_BDY2D_COND_TYPE  (111)
